services:
  - docker

sudo: false
language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master

env:
  - GO111MODULE=on

before_script:
  - go get -u golang.org/x/lint/golint

install:
  - go get -d -t ./...

script:
  - make ci
