services:
  - docker

sudo: false
language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

env:
  - GO111MODULE=on

before_script:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/stretchr/testify
  - go get -u github.com/mattn/go-sqlite3

install:
  - go get -d -t ./...

script:
  - make ci
